apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "longhorn-rebalancing-controller.fullname" . }}
  labels:
    {{- include "longhorn-rebalancing-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["longhorn.io"]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["longhorn.io"]
    resources: ["replicas"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["longhorn.io"]
    resources: ["volumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
