apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "longhorn-rebalancing-controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "longhorn-rebalancing-controller.labels" . | nindent 4 }}
automountServiceAccountToken: false
